apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: add-todo
  namespace: project
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: juslesan/todo-cron
            env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proj-postgre
                  key: POSTGRESQL_PASSWORD
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: proj-configmap
                  key: postgresql_database
          restartPolicy: OnFailure