apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- todo/manifests/deployment.yaml
- todo/prod_manifests/service.yaml
- todo/prod_manifests/ingress.yaml

- todo-back/manifests/configmap.yaml
- todo-back/manifests/postgre-service.yaml
- todo-back/manifests/postgres-secrets.yaml
- todo-back/prod_manifests/service.yaml
- todo-back/prod_manifests/statefulset.yaml
- todo-back/manifests/deployment.yaml

- cronjob/manifests/cronjob.yaml

- image-service/prod_manifests/service.yaml
- image-service/manifests/deployment.yaml
- image-service/prod_manifests/persistentvolumeclaim.yaml

images:
- name: PROJECT/FRONT_IMAGE
  newName: juslesan/todo
- name: PROJECT/BACK-IMAGE
  newName: juslesan/todo-back
- name: PROJECT/CRON
  newName: juslesan/todo-cron
- name: PROJECT/IMAGE
  newName: juslesan/todo-image