apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: todo-back
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-back
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-rate
      - pause:
          duration: 10m
      - setWeight: 50
  template:
    metadata:
      labels:
        app: todo-back
    spec:
      containers:
        - name: todo
          image: PROJECT/BACK-IMAGE
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: proj-postgre
                key: POSTGRESQL_PASSWORD
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: proj-configmap
                key: postgresql_database
          resources:
            limits:
              cpu: "150m"
              memory: "200Mi"
          readinessProbe:
            initialDelaySeconds: 15
            periodSeconds: 5
            httpGet:
               path: /health
               port: 3011