apiVersion: v1
kind: Service
metadata:
  name: image-svc
  namespace: project
spec:
  type: NodePort
  selector:
    app: image-service
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3012