apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-back
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-back
  template:
    metadata:
      labels:
        app: todo-back
    spec:
      containers:
        - name: todo
          image: juslesan/todo-back
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: proj-postgre
                key: POSTGRESQL_PASSWORD
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: proj-configmap
                key: postgresql_database