apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: image-service
          image: PROJECT/IMAGE
          volumeMounts:
          - name: shared-files
            mountPath: /usr/src/app/files
          resources:
            limits:
              cpu: "200m"
              memory: "200Mi"