apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main
  name: status200
spec:
  replicas: 1
  selector:
    matchLabels:
      app: status200
  template:
    metadata:
      labels:
        app: status200
    spec:
      containers:
        - name: status200
          image: juslesan/status200
