apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: main
  name: pingpong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
        - name: pingpong
          image: juslesan/pingpong
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgre
                key: POSTGRESQL_PASSWORD
          - name: POSTGRES_DATABASE
            valueFrom:
              configMapKeyRef:
                name: main-configmap
                key: postgresql_database
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"