apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgre
  namespace: main
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgB+Ml0L6fsjG9gGUSlGAvDnLdNuWzQ+DexUmfqatJu/q9yPdEIsMKc8qmoicT2XARVcvpxZGdFvr+4uK9VE/eHuit4cILp2xCTdJZ/eClGjQ55DFHiilBVK8ZPuLtvn7smueTzvAlpaZGO7X9aewJUMNX5/q49We8SNVSLsqD0egyK78daMnd7Q4DqpjpGw4j6BGEap9S3HIdsrKuyKCMz8QS/LuxZJG9uPmJUGowLryDZDxs+o2+KQ/0uYY34qldJHPJNoDAEj1PRaiMOluqtQj/aYYN+1OyuhwJvXDCfLDsFaufM4RHpO73ML3kbqCElMZATSZ9I17dDtKefS0M9H8olB1BNqwP/R2ZH0ObkBVRRY6EyRedjwOiNmVqJr52igjcQhqBso8OKYPUrKpg50KsG4BAVTtFhE9Q8Wgxrg0TMlFqHuXO2b+R+/U0ey27d8khaAyD+dzu+QR+rLA6RsoTtS44VI/IPbJQFvJjWVZp/67zZiC+vO100DYyAM0mdL90DuUHVJ78xa6QD/P1I+9Fc3LKMqTEYsi0F2h/AFdqptTfl855jXeKAlRHhxXH4LFR5FfO3THwZC1yYRqIm1wij1sPjAW4yrDpSmJutmaUfmP5G2yEYPtp0USmJ+ih/J6LYV9F59dHdtxshZL350gYHL7BuWUxkQ5izCS7BCc0Y2LnCRPblPvtnao+raRneuTxmJhRPxVr6B9Kcb04QAC01dtGpbzcJshF/rwFOrjB26oHdZEF59FmE=
  template:
    metadata:
      creationTimestamp: null
      name: postgre
      namespace: main

