apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgre
  namespace: main
spec:
  encryptedData:
    POSTGRESQL_PASSWORD: AgBTWyvFdhp6W2336WhqHAbvFVlLGNKFOUPZdqLOfppEOm37a1gh0/WGfIjluQRandXCf4ZuiLqh7eD/VzeaUxqT/xWWY/+BUThK2EGhYUo+gsChSQ7AVpSEJ6aD+UGcOQtdXkPjo7xugvOmslXmtpjKuqu7qnyx8V8nFhCDlLBkXeajZpowSKJP/IATuPHJNkO08YGzTgpyPP7KVfz8uGxmKTg3Ty8BYoY/Su0JvsjQkaKF6GKtKXRIMTQZqj+7oSS3KxW9eRyc6Vf/hS3eIagHcU5bVISMtHWeCTx1jpI4zO2tf04A8l3O54ATgzKL49c501HqoNr6RS5t1XwImGq+lEmBCQx4iYRY/3kcoJECk7Wxa+qLRERVWq+nwWnL/fWO5Fv82z82WgambVKXQQi7CHYHJSxWMqg3WdHubY9NuevulVmU4+eRZklBfru2sIq5Or2pFyhwFfxTp6ZhA725AghWyKd3za1UJiwhzmdnVrxQn8qwSpEovNvzokE/ZdWqRHdSTvNPpOUzocLVMB9rGAeA+zbUm0NdCjMIOmklDeC3J9xYfhipGH6RAlb3EUW5u1Nj6WPnpzLbsFNTZzXC5mh3X167muSrMOA0ny1EEB+ergS/VgcUtXMxp35+kmFAUdftFm0T2DgNjnjq5S4CBN+gM+cZOurNyPZ26LLxalXy1+TUQhbYIgg3JqyV7SgozENfRkJ+GS3q/4Ev6t+X88KX9U0r2CTJ3VCjCJlEA1WVRBlBt3VOZTg=
  template:
    metadata:
      creationTimestamp: null
      name: postgre
      namespace: main

