apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: juslesan/broadcaster
          resources:
            limits:
              cpu: "250m"
              memory: "100Mi"
          env:
            - name: NATS_URL
              value: nats://my-nats.default:4222
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-bot-token
                  key: TOKEN