apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      volumes:
        - name: shared-files
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: image-service
          image: juslesan/todo-image
          volumeMounts:
          - name: shared-files
            mountPath: /usr/src/app/files