name: Delete Branch Release

on:
  delete:
    paths:
      - '.github/workflows/project.yml'
      - 'course/project/**'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  TODO_FRONT_IMAGE: juslesan/todo
  TODO_BACK_IMAGE: juslesan/todo-back
  TODO_IMAGE_IMAGE: juslesan/todo-image
  TODO_CRON_IMAGE: juslesan/todo-cron

jobs:
  setup-build-publish-deploy:
    name: Setup, Delete
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - run: |-
        gcloud --quiet auth configure-docker

    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

# Deploy the Docker image to the GKE cluster
    - name: Delete
      run: |-
        kubectl delete namespace project-${{ github.event.ref }} || true