name: Release Project

on:
  push:
    branches: 
      - main
    paths:
      - "course/project/*"

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  TODO_FRONT_IMAGE: juslesan/todo
  TODO_BACK_IMAGE: juslesan/todo-back
  TODO_IMAGE_IMAGE: juslesan/todo-image
  TODO_CRON_IMAGE: juslesan/todo-cron

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - run: |-
        gcloud --quiet auth configure-docker

    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Build
      run: |-
        docker build --tag "gcr.io/$PROJECT_ID/$TODO_FRONT_IMAGE:$GITHUB_SHA" todo
        docker build --tag "gcr.io/$PROJECT_ID/$TODO_BACK_IMAGE:$GITHUB_SHA" todo-back
        docker build --tag "gcr.io/$PROJECT_ID/$TODO_IMAGE_IMAGE:$GITHUB_SHA" image-service
        docker build --tag "gcr.io/$PROJECT_ID/$TODO_CRON_IMAGE:$GITHUB_SHA" cronjob

# Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$TODO_FRONT_IMAGE:$GITHUB_SHA"
        docker push "gcr.io/$PROJECT_ID/$TODO_BACK_IMAGE:$GITHUB_SHA"
        docker push "gcr.io/$PROJECT_ID/$TODO_IMAGE_IMAGE:$GITHUB_SHA"
        docker push "gcr.io/$PROJECT_ID/$TODO_CRON_IMAGE:$GITHUB_SHA"

# Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

# Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl kustomize .
        kubectl apply -k .
        kubectl rollout status deployment/$TODO_FRONT_IMAGE
        kubectl rollout status deployment/$TODO_BACK_IMAGE
        kubectl rollout status deployment/$TODO_IMAGE_IMAGE
        kubectl rollout status deployment/$TODO_CRON_IMAGE
        kubectl get services -o wide